# Generated by Django 4.2.30 on 2026-07-09 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devotional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('bible_passage', models.CharField(max_length=150)),
                ('bible_text', models.TextField()),
                ('content', models.TextField()),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], db_index=True, default='DRAFT', max_length=20)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devotionals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'devocional',
                'verbose_name_plural': 'devocionales',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
