# Generated by Django 4.2.30 on 2026-08-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotionals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotional',
            name='bible_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
