# Generated by Django 4.2.30 on 2026-07-23 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Todos'), ('LEADERS', 'Líderes de Célula'), ('MEMBERS', 'Miembros Registrados'), ('USER', 'Usuario Específico')], default='ALL', max_length=20),
        ),
    ]
