# Generated by Django 4.2.30 on 2026-08-05 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
        ('notifications', '0002_notification_target_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='cells.cellgroup'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Todos'), ('LEADERS', 'Líderes de Célula'), ('MEMBERS', 'Miembros Registrados'), ('USER', 'Usuario Específico'), ('CELL', 'Miembros de una Célula')], default='ALL', max_length=20),
        ),
    ]
