# Generated by Django 4.2.30 on 2026-08-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_target_cell_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='deep_link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
