# Generated by Django 4.2.30 on 2026-08-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notification_deep_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='target_audience',
            field=models.CharField(choices=[('ALL', 'Todos'), ('LEADERS', 'Líderes de Célula'), ('MEMBERS', 'Miembros Registrados'), ('USER', 'Usuario Específico'), ('CELL', 'Miembros de una Célula'), ('PASTORS', 'Pastorado')], default='ALL', max_length=20),
        ),
    ]
