# Generated by Django 4.2.30 on 2026-08-08 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0003_cell_hierarchy_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPERADMIN', 'Super Administrador'), ('ADMIN', 'Pastor / Administrador General'), ('COORDINATOR', 'Coordinador de Células'), ('CONTENT_EDITOR', 'Editor de Contenido'), ('CELL_LEADER', 'Líder de Célula'), ('SUPPORT', 'Soporte y Consejería'), ('MEMBER', 'Miembro de la Comunidad'), ('VIEWER', 'Visitante/Espectador')], db_index=True, max_length=50, unique=True),
        ),
    ]
