# Generated by Django 4.2.30 on 2026-07-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date', models.DateField(db_index=True)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audio_url', models.URLField(blank=True, max_length=500, null=True)),
                ('sermon_notes', models.TextField(blank=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('is_live', models.BooleanField(db_index=True, default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'servicio religioso',
                'verbose_name_plural': 'servicios religiosos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=100)),
                ('chapter', models.PositiveIntegerField()),
                ('verses', models.CharField(help_text='ej. 1-5 o 12', max_length=50)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='services.churchservice')),
            ],
            options={
                'verbose_name': 'versículo del servicio',
                'verbose_name_plural': 'versículos del servicio',
            },
        ),
    ]
