# Generated by Django 4.2.30 on 2026-07-09 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(default='Génesis App', max_length=100)),
                ('app_description', models.TextField(blank=True)),
                ('splash_text', models.CharField(default='Una casa para todos', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='settings/')),
                ('primary_color', models.CharField(default='#032F2F', max_length=7)),
                ('secondary_color', models.CharField(default='#D4AF37', max_length=7)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('terms_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'configuración de aplicación',
                'verbose_name_plural': 'configuración de aplicación',
            },
        ),
        migrations.CreateModel(
            name='ChurchSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('church_name', models.CharField(default='Iglesia Génesis', max_length=150)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('whatsapp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'configuración de iglesia',
                'verbose_name_plural': 'configuración de iglesia',
            },
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MONDAY', 'Lunes'), ('TUESDAY', 'Martes'), ('WEDNESDAY', 'Miércoles'), ('THURSDAY', 'Jueves'), ('FRIDAY', 'Viernes'), ('SATURDAY', 'Sábado'), ('SUNDAY', 'Domingo')], db_index=True, max_length=15)),
                ('start_time', models.TimeField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'horario de servicio',
                'verbose_name_plural': 'horarios de servicios',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('icon_name', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name': 'red social',
                'verbose_name_plural': 'redes sociales',
            },
        ),
    ]
