# Generated by Django 4.2.30 on 2026-07-09 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('summary', models.TextField(blank=True)),
                ('content', models.TextField()),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='publications/covers/')),
                ('content_type', models.CharField(choices=[('NEWS', 'Noticia'), ('SERVICE', 'Servicio realizado'), ('DEVOTIONAL', 'Devocional'), ('EVENT', 'Evento'), ('YOUTH', 'Jóvenes'), ('GENERAL', 'General')], db_index=True, default='GENERAL', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SCHEDULED', 'Programado'), ('PUBLISHED', 'Publicado'), ('ARCHIVED', 'Archivado')], db_index=True, default='DRAFT', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_featured', models.BooleanField(db_index=True, default=False)),
                ('show_in_app', models.BooleanField(db_index=True, default=True)),
                ('send_notification', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('seo_title', models.CharField(blank=True, max_length=150)),
                ('seo_description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'publicación',
                'verbose_name_plural': 'publicaciones',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PublicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoría de publicación',
                'verbose_name_plural': 'categorías de publicaciones',
            },
        ),
        migrations.CreateModel(
            name='PublicationTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'etiqueta de publicación',
                'verbose_name_plural': 'etiquetas de publicaciones',
            },
        ),
        migrations.CreateModel(
            name='PublicationGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='publications/gallery/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='publications.publication')),
            ],
            options={
                'verbose_name': 'imagen de galería',
                'verbose_name_plural': 'imágenes de galería',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='publication',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publications', to='publications.publicationcategory'),
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='publications', to='publications.publicationtag'),
        ),
    ]
