# Generated by Django 4.2.30 on 2026-07-09 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='publicationcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='publicationtag',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
