# Generated by Django 4.2.30 on 2026-08-08 20:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellgroup',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_cells', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MemberFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CALL', 'Llamada'), ('VISIT', 'Visita'), ('MESSAGE', 'Mensaje'), ('OTHER', 'Otro')], default='CALL', max_length=20)),
                ('date', models.DateField(db_index=True)),
                ('summary', models.TextField()),
                ('needs_attention', models.BooleanField(default=False, help_text='Marca a quien requiere seguimiento cercano.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='cells.cellgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to=settings.AUTH_USER_MODEL)),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_follow_ups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'seguimiento de miembro',
                'verbose_name_plural': 'seguimientos de miembros',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CellMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, verbose_name='observaciones')),
                ('guests_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='cells.cellgroup')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_meetings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reunión de célula',
                'verbose_name_plural': 'reuniones de célula',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Asistió'), ('ABSENT', 'No asistió'), ('LATE', 'Tardanza'), ('EXCUSED', 'Justificado')], db_index=True, default='PRESENT', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='cells.cellmeeting')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['member__first_name', 'member__email'],
            },
        ),
        migrations.AddConstraint(
            model_name='cellmeeting',
            constraint=models.UniqueConstraint(fields=('cell', 'date'), name='unique_meeting_per_cell_and_date'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('meeting', 'member'), name='unique_attendance_per_meeting'),
        ),
    ]
