# Generated by Django 4.2.30 on 2026-08-08 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cells', '0002_cellgroup_coordinator_memberfollowup_cellmeeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CellReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('summary', models.TextField(verbose_name='cómo le fue a la célula')),
                ('highlights', models.TextField(blank=True, verbose_name='lo más destacado')),
                ('challenges', models.TextField(blank=True, verbose_name='dificultades')),
                ('prayer_needs', models.TextField(blank=True, verbose_name='motivos de oración')),
                ('meetings_held', models.PositiveIntegerField(default=0)),
                ('average_attendance', models.FloatField(default=0)),
                ('new_members', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviado'), ('REVIEWED', 'Revisado')], db_index=True, default='DRAFT', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, verbose_name='respuesta del coordinador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='cells.cellgroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_cell_reports', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_cell_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'informe de célula',
                'verbose_name_plural': 'informes de célula',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
    ]
