# Generated by Django 4.2.30 on 2026-08-08 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0003_cellreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellreport',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='cell_reports/'),
        ),
        migrations.AddField(
            model_name='cellreport',
            name='photo_caption',
            field=models.CharField(blank=True, max_length=255, verbose_name='pie de foto'),
        ),
    ]
