# Generated by Django 4.2.30 on 2026-08-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0004_cellreport_photo_cellreport_photo_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='cellreport',
            name='kind',
            field=models.CharField(choices=[('ACTIVITY', 'Actividad de la célula'), ('DEVOTIONAL', 'Devocional')], db_index=True, default='ACTIVITY', max_length=20),
        ),
        migrations.CreateModel(
            name='CellReportPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cell_reports/')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='pie de foto')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='cells.cellreport')),
            ],
            options={
                'verbose_name': 'imagen de informe',
                'verbose_name_plural': 'imágenes de informe',
                'ordering': ['position', 'id'],
            },
        ),
    ]
