# Generated by Django 4.2.30 on 2026-07-09 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('age_range', models.CharField(choices=[('YOUTH', '15-25 años'), ('YOUNG_ADULT', '26-35 años'), ('ADULT', '36-50 años'), ('SENIOR', '51+ años'), ('PREFER_NOT_SAY', 'Prefiero no decir')], default='PREFER_NOT_SAY', max_length=20)),
                ('how_did_you_find_us', models.CharField(choices=[('SOCIAL_MEDIA', 'Redes sociales'), ('FRIEND_FAMILY', 'Amigo o familiar'), ('WEBSITE', 'Página web'), ('STREET', 'Pasé por la iglesia'), ('EVENT', 'Evento'), ('OTHER', 'Otro')], default='OTHER', max_length=30)),
                ('message', models.TextField(blank=True)),
                ('preferred_contact', models.CharField(choices=[('EMAIL', 'Correo electrónico'), ('PHONE', 'Llamada telefónica'), ('WHATSAPP', 'WhatsApp')], default='WHATSAPP', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('RESOLVED', 'Resuelto'), ('ARCHIVED', 'Archivado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas del seguimiento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visitor_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_email', models.EmailField(blank=True, max_length=254)),
                ('requester_phone', models.CharField(blank=True, max_length=30)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('IN_PROGRESS', 'En proceso'), ('RESOLVED', 'Resuelto'), ('ARCHIVED', 'Archivado')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notas internas para el pastor/líder')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
