# Generated by Django 4.2.30 on 2026-07-22 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cells', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('church_requests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorrequest',
            name='cell_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_requests', to='cells.cellgroup'),
        ),
        migrations.AddField(
            model_name='visitorrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cell_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
