# Generated by Django 4.2.30 on 2026-07-10 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('file', models.FileField(upload_to='multimedia/')),
                ('file_type', models.CharField(choices=[('IMAGE', 'Imagen'), ('PDF', 'Documento PDF'), ('AUDIO', 'Audio'), ('VIDEO', 'Video'), ('OTHER', 'Otro')], db_index=True, default='OTHER', max_length=20)),
                ('file_size', models.IntegerField(blank=True, help_text='Tamaño del archivo en bytes', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_multimedia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Multimedia',
                'verbose_name_plural': 'Biblioteca Multimedia',
                'ordering': ['-created_at'],
            },
        ),
    ]
